// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/interfaces/IERC4626.sol";

/**
 * @title IYieldVault
 * @notice Extended ERC-4626 interface for yield-generating vaults
 * @dev Adds yield tracking and distribution functionality to standard ERC-4626
 */
interface IYieldVault is IERC4626 {
    /**
     * @notice Get the accumulated yield for a user
     * @param user Address of the user
     * @return Yield amount in asset tokens
     */
    function getUserYield(address user) external view returns (uint256);

    /**
     * @notice Claim accumulated yield
     * @return Amount of yield claimed
     */
    function claimYield() external returns (uint256);

    /**
     * @notice Get the current APY (Annual Percentage Yield)
     * @return APY in basis points (e.g., 650 = 6.5%)
     */
    function getAPY() external view returns (uint256);

    /**
     * @notice Get total yield generated by the vault
     * @return Total yield amount
     */
    function getTotalYieldGenerated() external view returns (uint256);

    /**
     * @notice Harvest yield from underlying protocol
     * @dev Called periodically to update yield balances
     */
    function harvestYield() external;

    // Events
    event YieldHarvested(uint256 amount, uint256 timestamp);
    event YieldClaimed(address indexed user, uint256 amount);
    event YieldDistributed(address indexed publicGoods, uint256 amount, address indexed protocol, uint256 protocolFee);
}
